services:
  db:
    image: timescale/timescaledb:latest-pg14    
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 127.0.01:5796:5432
    volumes:
      - data:/var/lib/postgresql/data
  vault-watcher:
    build: .

volumes:
  data: