services:
  db:
    env_file: config.env
    image: timescale/timescaledb:latest-pg14   
    ports:
      - 127.0.0.1:${DB_PORT}:5432
    volumes:
      - data:/var/lib/postgresql/data
  vault-watcher:
    env_file: config.env
    build: .
  grafana:
    env_file: config.env
    image: grafana/grafana:latest
    ports:
      - 127.0.0.1:3000:3000
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/home.json:/usr/share/grafana/public/home.json

volumes:
  data: